FROM golang:alpine

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

ENV REQUEST_ORIGIN=http://localhost:5000

RUN go build && addgroup -S appgroup && adduser -S appuser -G appgroup

USER appuser

CMD ["./server"]
