FROM alpine

WORKDIR /usr/src/app

COPY script.sh .

RUN apk --no-cache add curl && addgroup -S appgroup && adduser -S appuser -G appgroup && chown appuser script.sh

USER appuser

RUN chmod +x script.sh

CMD ./script.sh
