FROM node:alpine

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

RUN npm install --loglevel verbose

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm run build && npm install -g serve && addgroup -S appgroup && adduser -S appuser -G appgroup && apk del zlib && apk del ssl_client && apk del scanelf

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]
